// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebsitePresentation.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221127143807_AddFileModel")]
    partial class AddFileModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "623f6767-6d00-42d2-8191-35160d46556f",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "515e934c-64a7-4010-96cf-de95abdc90ea",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "739c371c-b349-41e5-bf79-11d930034337",
                            Name = "Add",
                            NormalizedName = "ADD"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "2bbe05d0-fabb-4f50-920a-ad3cd9a50291",
                            Name = "Edit",
                            NormalizedName = "EDIT"
                        },
                        new
                        {
                            Id = "5",
                            ConcurrencyStamp = "49079709-01a5-4d8a-8e59-8906a37ee021",
                            Name = "Delete",
                            NormalizedName = "DELETE"
                        },
                        new
                        {
                            Id = "6",
                            ConcurrencyStamp = "c82c87f3-bf10-4332-8cf2-9b049f5633f5",
                            Name = "FullWriter",
                            NormalizedName = "FULLWRITER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Model.SectionFirstStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("SectionFirstSteps");
                });

            modelBuilder.Entity("Model.SectionPostAnswerStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_SectionPostCommentStep")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id_SectionPostCommentStep");

                    b.ToTable("SectionPostAnswerSteps");
                });

            modelBuilder.Entity("Model.SectionPostCommentStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_SectionPostStep")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id_SectionPostStep");

                    b.ToTable("SectionPostCommentSteps");
                });

            modelBuilder.Entity("Model.SectionPostFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_SectionPostStep")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_SectionPostStep");

                    b.ToTable("SectionPostFile");
                });

            modelBuilder.Entity("Model.SectionPostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_SectionPostStep")
                        .HasColumnType("int");

                    b.Property<string>("PictureAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_SectionPostStep");

                    b.ToTable("SectionPostImages");
                });

            modelBuilder.Entity("Model.SectionPostSocialVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SectionPostSocialVideos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Address = "",
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2858),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2863),
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2861),
                            TagsName = "یوتیوب",
                            Timable = false,
                            Title = "Youtube"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Address = "",
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2870),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2876),
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2873),
                            TagsName = "فەیسبوک",
                            Timable = false,
                            Title = "FaceBook"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Address = "",
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2883),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2889),
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2886),
                            TagsName = "تێلێگرام",
                            Timable = false,
                            Title = "Telegram"
                        });
                });

            modelBuilder.Entity("Model.SectionPostStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_SectionPostType")
                        .HasColumnType("int");

                    b.Property<int>("Id_SectionThirdStep")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewsNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_SectionPostType");

                    b.HasIndex("Id_SectionThirdStep");

                    b.ToTable("SectionPostSteps");
                });

            modelBuilder.Entity("Model.SectionPostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SectionPostTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2794),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2800),
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2797),
                            TagsName = "نوسراوە",
                            Timable = false,
                            Title = "Article"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2807),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2812),
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2810),
                            TagsName = "ویدیۆ",
                            Timable = false,
                            Title = "Video"
                        });
                });

            modelBuilder.Entity("Model.SectionPostVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_SectionPostSocialVideo")
                        .HasColumnType("int");

                    b.Property<int>("Id_SectionPostStep")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_SectionPostSocialVideo");

                    b.HasIndex("Id_SectionPostStep");

                    b.ToTable("SectionPostVideos");
                });

            modelBuilder.Entity("Model.SectionSecondStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_SectionFirstStep")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id_SectionFirstStep");

                    b.ToTable("SectionSecondSteps");
                });

            modelBuilder.Entity("Model.SectionThirdStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_SectionSecondStep")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id_SectionSecondStep");

                    b.ToTable("SectionThirdSteps");
                });

            modelBuilder.Entity("Model.WebsiteActiveTimeControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.Property<string>("WebsiteTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebsiteActiveTimeControls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2588),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2599),
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2592),
                            TagsName = "وێب سایت",
                            Timable = false,
                            WebsiteTitle = "ناوی وێب سایت"
                        });
                });

            modelBuilder.Entity("Model.WebsiteAdminsControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TellphoneNmber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WebsiteAdminsControls");
                });

            modelBuilder.Entity("Model.WebsiteThemControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Timable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("WebsiteThemControls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2924),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2930),
                            SectionName = "RightSection",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2927),
                            TagsName = "RightSection",
                            Timable = false
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2940),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2945),
                            SectionName = "Header",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2943),
                            TagsName = "Header",
                            Timable = false
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2952),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2958),
                            SectionName = "HeaderLeft",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2955),
                            TagsName = "HeaderLeft",
                            Timable = false
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2965),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2970),
                            SectionName = "HeaderCenter",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2968),
                            TagsName = "HeaderCenter",
                            Timable = false
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2976),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2982),
                            SectionName = "HeaderRight",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2979),
                            TagsName = "HeaderRight",
                            Timable = false
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2988),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2994),
                            SectionName = "Search",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(2991),
                            TagsName = "Search",
                            Timable = false
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3000),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3005),
                            SectionName = "Marquee",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3002),
                            TagsName = "Marquee",
                            Timable = false
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3011),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3017),
                            SectionName = "LeftSection",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3014),
                            TagsName = "LeftSection",
                            Timable = false
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3023),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3029),
                            SectionName = "Footer",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3026),
                            TagsName = "Footer",
                            Timable = false
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3035),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3040),
                            SectionName = "News",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3038),
                            TagsName = "News",
                            Timable = false
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3046),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3052),
                            SectionName = "SectionVideo",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3049),
                            TagsName = "SectionVideo",
                            Timable = false
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3058),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3063),
                            SectionName = "SectionArticle",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3061),
                            TagsName = "SectionArticle",
                            Timable = false
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3070),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3075),
                            SectionName = "MostViewd",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3073),
                            TagsName = "MostViewd",
                            Timable = false
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3081),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3087),
                            SectionName = "ThirdStepCategories",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3084),
                            TagsName = "ThirdStepCategories",
                            Timable = false
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3093),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3099),
                            SectionName = "ViewSubCategoryPosts",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3096),
                            TagsName = "ViewSubCategoryPosts",
                            Timable = false
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3105),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3110),
                            SectionName = "ViewPost",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3108),
                            TagsName = "ViewPost",
                            Timable = false
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3117),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3122),
                            SectionName = "RelatedPost",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3119),
                            TagsName = "RelatedPost",
                            Timable = false
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3128),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3134),
                            SectionName = "ViewComment",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3131),
                            TagsName = "ViewComment",
                            Timable = false
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CreateDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3140),
                            Email = "NejatRahmani68@gmail.com",
                            EndDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3145),
                            SectionName = "InsertComment",
                            StartDate = new DateTime(2022, 11, 27, 15, 38, 7, 39, DateTimeKind.Local).AddTicks(3143),
                            TagsName = "InsertComment",
                            Timable = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.SectionPostAnswerStep", b =>
                {
                    b.HasOne("Model.SectionPostCommentStep", "SectionPostCommentStep")
                        .WithMany("SectionPostAnswerSteps")
                        .HasForeignKey("Id_SectionPostCommentStep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionPostCommentStep");
                });

            modelBuilder.Entity("Model.SectionPostCommentStep", b =>
                {
                    b.HasOne("Model.SectionPostStep", "SectionPostStep")
                        .WithMany("SectionPostCommentSteps")
                        .HasForeignKey("Id_SectionPostStep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionPostStep");
                });

            modelBuilder.Entity("Model.SectionPostFile", b =>
                {
                    b.HasOne("Model.SectionPostStep", "SectionPostStep")
                        .WithMany("SectionPostFiles")
                        .HasForeignKey("Id_SectionPostStep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionPostStep");
                });

            modelBuilder.Entity("Model.SectionPostImage", b =>
                {
                    b.HasOne("Model.SectionPostStep", "SectionPostStep")
                        .WithMany("SectionPostImages")
                        .HasForeignKey("Id_SectionPostStep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionPostStep");
                });

            modelBuilder.Entity("Model.SectionPostStep", b =>
                {
                    b.HasOne("Model.SectionPostType", "SectionPostType")
                        .WithMany("SectionPostSteps")
                        .HasForeignKey("Id_SectionPostType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.SectionThirdStep", "SectionThirdStep")
                        .WithMany("SectionPostSteps")
                        .HasForeignKey("Id_SectionThirdStep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionPostType");

                    b.Navigation("SectionThirdStep");
                });

            modelBuilder.Entity("Model.SectionPostVideo", b =>
                {
                    b.HasOne("Model.SectionPostSocialVideo", "SectionPostSocialVideo")
                        .WithMany("SectionPostVideos")
                        .HasForeignKey("Id_SectionPostSocialVideo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.SectionPostStep", "SectionPostStep")
                        .WithMany("SectionPostVideos")
                        .HasForeignKey("Id_SectionPostStep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionPostSocialVideo");

                    b.Navigation("SectionPostStep");
                });

            modelBuilder.Entity("Model.SectionSecondStep", b =>
                {
                    b.HasOne("Model.SectionFirstStep", "SectionFirstStep")
                        .WithMany("SectionSecondSteps")
                        .HasForeignKey("Id_SectionFirstStep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionFirstStep");
                });

            modelBuilder.Entity("Model.SectionThirdStep", b =>
                {
                    b.HasOne("Model.SectionSecondStep", "SectionSecondStep")
                        .WithMany("SectionThirdSteps")
                        .HasForeignKey("Id_SectionSecondStep")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SectionSecondStep");
                });

            modelBuilder.Entity("Model.SectionFirstStep", b =>
                {
                    b.Navigation("SectionSecondSteps");
                });

            modelBuilder.Entity("Model.SectionPostCommentStep", b =>
                {
                    b.Navigation("SectionPostAnswerSteps");
                });

            modelBuilder.Entity("Model.SectionPostSocialVideo", b =>
                {
                    b.Navigation("SectionPostVideos");
                });

            modelBuilder.Entity("Model.SectionPostStep", b =>
                {
                    b.Navigation("SectionPostCommentSteps");

                    b.Navigation("SectionPostFiles");

                    b.Navigation("SectionPostImages");

                    b.Navigation("SectionPostVideos");
                });

            modelBuilder.Entity("Model.SectionPostType", b =>
                {
                    b.Navigation("SectionPostSteps");
                });

            modelBuilder.Entity("Model.SectionSecondStep", b =>
                {
                    b.Navigation("SectionThirdSteps");
                });

            modelBuilder.Entity("Model.SectionThirdStep", b =>
                {
                    b.Navigation("SectionPostSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
